<?php

/**
 * This is the model base class for the table "{{quiz}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Quiz".
 *
 * Columns in table "{{quiz}}" available as properties of the model,
 * followed by relations of table "{{quiz}}" available as properties of the model.
 *
 * @property string $id
 * @property string $learner_id
 * @property string $concept_id
 * @property string $score
 * @property integer $type
 * @property string $create_at
 * @property string $done_at
 * @property string $lastaccess_at
 *
 * @property Concept $concept
 * @property User $learner
 * @property mixed $questions
 */
abstract class BaseQuiz extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{quiz}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Quiz|Quizzes', $n);
	}

	public static function representingColumn() {
		return 'create_at';
	}

	public function rules() {
		return array(
			array('learner_id, concept_id, create_at', 'required'),
			array('learner_id, concept_id', 'length', 'max'=>10),
			array('score', 'length', 'max'=>5),
			array('done_at, lastaccess_at', 'safe'),
			array('score, done_at, lastaccess_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, learner_id, concept_id, score, create_at, done_at, lastaccess_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'concept' => array(self::BELONGS_TO, 'Concept', 'concept_id'),
			'learner' => array(self::BELONGS_TO, 'User', 'learner_id'),
			'questions' => array(self::MANY_MANY, 'Question', '{{quiz_question}}(quiz_id, question_id)'),
		);
	}

	public function pivotModels() {
		return array(
			'questions' => 'QuizQuestion',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'learner_id' => null,
			'concept_id' => null,
			'score' => Yii::t('app', 'Score'),
			'type' => Yii::t('app', 'Type'),
			'create_at' => Yii::t('app', 'Create At'),
			'done_at' => Yii::t('app', 'Done At'),
			'lastaccess_at' => Yii::t('app', 'Lastaccess At'),
			'concept' => null,
			'learner' => null,
			'questions' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('learner_id', $this->learner_id);
		$criteria->compare('concept_id', $this->concept_id);
		$criteria->compare('score', $this->score, true);
		$criteria->compare('type', $this->type);
		$criteria->compare('create_at', $this->create_at, true);
		$criteria->compare('done_at', $this->done_at, true);
		$criteria->compare('lastaccess_at', $this->lastaccess_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}