<?php

/**
 * This is the model base class for the table "{{feed_comment}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "FeedComment".
 *
 * Columns in table "{{feed_comment}}" available as properties of the model,
 * followed by relations of table "{{feed_comment}}" available as properties of the model.
 *
 * @property string $id
 * @property string $user_id
 * @property string $feed_id
 * @property string $description
 * @property string $create_at
 *
 * @property User $user
 * @property Feed $feed
 */
abstract class BaseFeedComment extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{feed_comment}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'FeedComment|FeedComments', $n);
	}

	public static function representingColumn() {
		return 'description';
	}

	public function rules() {
		return array(
			array('user_id, feed_id, description, create_at', 'required'),
			array('user_id, feed_id', 'length', 'max'=>10),
			array('id, user_id, feed_id, description, create_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
			'feed' => array(self::BELONGS_TO, 'Feed', 'feed_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'feed_id' => null,
			'description' => Yii::t('app', 'Description'),
			'create_at' => Yii::t('app', 'Create At'),
			'user' => null,
			'feed' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('feed_id', $this->feed_id);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('create_at', $this->create_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}