<?php

/**
 * This is the model base class for the table "{{concept_comment}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ConceptComment".
 *
 * Columns in table "{{concept_comment}}" available as properties of the model,
 * followed by relations of table "{{concept_comment}}" available as properties of the model.
 *
 * @property string $id
 * @property string $concept_id
 * @property string $learner_id
 * @property string $description
 * @property string $create_at
 *
 * @property Concept $concept
 * @property User $learner
 */
abstract class BaseConceptComment extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{concept_comment}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ConceptComment|ConceptComments', $n);
	}

	public static function representingColumn() {
		return 'description';
	}

	public function rules() {
		return array(
			array('concept_id, description', 'required'),
			array('concept_id, learner_id', 'length', 'max'=>10),
			array('id, concept_id, learner_id, description, create_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'concept' => array(self::BELONGS_TO, 'Concept', 'concept_id'),
			'learner' => array(self::BELONGS_TO, 'User', 'learner_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'concept_id' => null,
			'learner_id' => null,
			'description' => Yii::t('app', 'Description'),
			'create_at' => Yii::t('app', 'Create At'),
			'concept' => null,
			'learner' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('concept_id', $this->concept_id);
		$criteria->compare('learner_id', $this->learner_id);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('create_at', $this->create_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}