<?php

/**
 * This is the model base class for the table "{{question_option}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "QuestionOption".
 *
 * Columns in table "{{question_option}}" available as properties of the model,
 * followed by relations of table "{{question_option}}" available as properties of the model.
 *
 * @property string $id
 * @property string $question_id
 * @property string $opt
 * @property string $val
 *
 * @property Question $question
 */
abstract class BaseQuestionOption extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{question_option}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'QuestionOption|QuestionOptions', $n);
	}

	public static function representingColumn() {
		return 'opt';
	}

	public function rules() {
		return array(
			array('opt, val', 'required'),
			array('question_id', 'length', 'max'=>10),
			array('opt', 'length', 'max'=>1),
			array('id, question_id, opt, val', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'question' => array(self::BELONGS_TO, 'Question', 'question_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'question_id' => null,
			'opt' => Yii::t('app', 'Opt'),
			'val' => Yii::t('app', 'Val'),
			'question' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('question_id', $this->question_id);
		$criteria->compare('opt', $this->opt, true);
		$criteria->compare('val', $this->val, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}