<?php

/**
 * This is the model base class for the table "{{question}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Question".
 *
 * Columns in table "{{question}}" available as properties of the model,
 * followed by relations of table "{{question}}" available as properties of the model.
 *
 * @property string $id
 * @property string $author_id
 * @property string $concept_id
 * @property string $description
 * @property string $correct_answer
 * @property string $create_at
 * @property string $update_at
 *
 * @property User $author
 * @property Concept $concept
 * @property QuestionOption[] $options
 * @property mixed $quizzes
 */
abstract class BaseQuestion extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{question}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Question|Questions', $n);
	}

	public static function representingColumn() {
		return 'description';
	}

	public function rules() {
		return array(
			array('concept_id, description, correct_answer', 'required'),
			array('author_id, concept_id', 'length', 'max'=>10),
			array('correct_answer', 'length', 'max'=>1),
			array('update_at', 'safe'),
			array('update_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, author_id, concept_id, description, correct_answer, create_at, update_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'author' => array(self::BELONGS_TO, 'User', 'author_id'),
			'concept' => array(self::BELONGS_TO, 'Concept', 'concept_id'),
			'options' => array(self::HAS_MANY, 'QuestionOption', 'question_id'),
			'quizzes' => array(self::MANY_MANY, 'Quiz', '{{quiz_question}}(question_id, quiz_id)'),
		);
	}

	public function pivotModels() {
		return array(
			'quizzes' => 'QuizQuestion',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'author_id' => null,
			'concept_id' => null,
			'description' => Yii::t('app', 'Description'),
			'correct_answer' => Yii::t('app', 'Correct Answer'),
			'create_at' => Yii::t('app', 'Create At'),
			'update_at' => Yii::t('app', 'Update At'),
			'author' => null,
			'concept' => null,
			'options' => null,
			'quizzes' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('author_id', $this->author_id);
		$criteria->compare('concept_id', $this->concept_id);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('correct_answer', $this->correct_answer, true);
		$criteria->compare('create_at', $this->create_at, true);
		$criteria->compare('update_at', $this->update_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}