<?php

/**
 * This is the model base class for the table "{{share}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Share".
 *
 * Columns in table "{{share}}" available as properties of the model,
 * followed by relations of table "{{share}}" available as properties of the model.
 *
 * @property string $id
 * @property string $user_id
 * @property string $of
 * @property string $of_id
 * @property string $description
 * @property string $create_at
 * @property string $update_at
 *
 * @property User $user
 */
abstract class BaseShare extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{share}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Share|Shares', $n);
	}

	public static function representingColumn() {
		return 'of';
	}

	public function rules() {
		return array(
			array('user_id, of, of_id, create_at', 'required'),
			array('user_id, of_id', 'length', 'max'=>10),
			array('of', 'length', 'max'=>255),
			array('description, update_at', 'safe'),
			array('description, update_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, of, of_id, description, create_at, update_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'of' => Yii::t('app', 'Of'),
			'of_id' => Yii::t('app', 'Of'),
			'description' => Yii::t('app', 'Description'),
			'create_at' => Yii::t('app', 'Create At'),
			'update_at' => Yii::t('app', 'Update At'),
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('of', $this->of, true);
		$criteria->compare('of_id', $this->of_id, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('create_at', $this->create_at, true);
		$criteria->compare('update_at', $this->update_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}