<?php

/**
 * This is the model base class for the table "{{concept_resource}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ConceptResource".
 *
 * Columns in table "{{concept_resource}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $concept_id
 * @property string $resource_id
 *
 */
abstract class BaseConceptResource extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{concept_resource}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ConceptResource|ConceptResources', $n);
	}

	public static function representingColumn() {
		return array(
			'concept_id',
			'resource_id',
		);
	}

	public function rules() {
		return array(
			array('concept_id, resource_id', 'required'),
			array('concept_id, resource_id', 'length', 'max'=>10),
			array('concept_id, resource_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'concept_id' => null,
			'resource_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('concept_id', $this->concept_id);
		$criteria->compare('resource_id', $this->resource_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}